name: Book it Build

on:
  push:
    branches:
      - dev
      - master
      - part4_dev

  pull_request:
    branches:
      - dev
      - master
      - part4_dev
<<<<<<< .merge_file_a20688
=======

>>>>>>> .merge_file_a27792



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1


      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.9

      - name: Run tests
        run: ./gradlew test



      - name: Build project
        run: ./gradlew assemble
      



