name: Book it Build

on:
  push:
    branches:
      - dev
      - master

  pull_request:
    branches:
      - dev
      - master



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1


      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.9

      - name: Run tests
        run: ./gradlew test


      - name: Build project
        run: ./gradlew assemble



